packages:
  # Apps directory - contains all applications
  - 'apps/*'

  # Libs directory - contains all libraries/packages
  - 'libs/*'

  # Packages directory - contains publishable npm packages
  - 'packages/*'

  # Tools directory if it contains packages
  - 'tools'
