packages:
  # Apps directory - contains all applications
  - 'apps/*'

  # Libs directory - contains all libraries/packages
  - 'libs/*'

  # Packages directory - contains publishable npm packages
  - 'packages/*'

  # Tools directory if it contains packages
  - 'tools'
catalog:
  es-main: ^1.4.0
patchedDependencies:
  nx@22.6.5: patches/nx@22.6.5.patch
