import unicodeNames from '@unicode/unicode-17.0.0/Names/index.js';
import controlAliases from '@unicode/unicode-17.0.0/Names/Control/index.js';
import correctionAliases from '@unicode/unicode-17.0.0/Names/Correction/index.js';
import abbreviationAliases from '@unicode/unicode-17.0.0/Names/Abbreviation/index.js';
import alternateAliases from '@unicode/unicode-17.0.0/Names/Alternate/index.js';
import { createRequire } from 'module';

// Use createRequire for JSON imports — avoids ESM import attribute requirement
// when this module is loaded transitively from vite.config.ts
const require = createRequire(import.meta.url);
// gemoji supplies GitHub-style :shortcodes: and search tags (not part of the UCD).
const gemojiData = require('gemoji') as {
  gemoji: Array<{ emoji: string; names: string[]; tags: string[] }>;
};

// Generated by scripts/generate-unicode-data.mjs (the version-bump mechanism).
// ageRanges: sorted [startCp, endCp, version] covering ALL Unicode versions.
// draftNames: [name, generalCategory] for code points the names package predates.
// emojiData: ordered base emoji parsed from emoji-test.txt (replaces unicode-emoji-json).
import { ageRanges } from '../src/generated/unicode-age';
import { draftNames } from '../src/generated/draft-names';
import { generatedMeta } from '../src/generated/meta';
import { emojiData } from '../src/generated/emoji';

import {
  CP437_SPECIAL,
  codePointsKey,
  compareVersionsDesc,
  type CharacterEntry,
  type UnicodeData,
} from '../src/unicode-data';

/** The newest Unicode version present in the generated data (e.g. "18.0"). */
export const LATEST_UNICODE_VERSION = generatedMeta.latestVersion;

/** Binary-search the sorted age ranges for the version a code point was introduced in. */
function versionForCodePoint(cp: number): string | null {
  let lo = 0;
  let hi = ageRanges.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    const [start, end, version] = ageRanges[mid];
    if (cp < start) hi = mid - 1;
    else if (cp > end) lo = mid + 1;
    else return version;
  }
  return null;
}

function draftName(cp: number): string {
  return draftNames[cp.toString(16).toUpperCase()]?.[0] ?? '';
}

/** Route a newly-materialized code point to a category based on its general category. */
function categoryForGeneralCategory(gc: string): string {
  // Symbols (Sm/Sc/Sk/So) and punctuation (P*) read as "symbols"; everything else
  // (letters, marks, numbers, ideographs — the bulk of new scripts) is CJK & Scripts.
  if (gc.startsWith('S') || gc.startsWith('P')) return 'symbols';
  return 'cjk-scripts';
}

// CP437 bidirectional maps
const altToUnicode = new Map<number, number>();
for (const [altCode, cp] of CP437_SPECIAL) altToUnicode.set(altCode, cp);
for (let i = 32; i <= 126; i++) altToUnicode.set(i, i);
const unicodeToAlt = new Map<number, number>();
for (const [altCode, cp] of altToUnicode.entries()) unicodeToAlt.set(cp, altCode);

function getAliases(cp: number): string[] {
  const out: string[] = [];
  const ctrl = controlAliases[cp];
  if (ctrl) out.push(...ctrl);
  const corr = correctionAliases[cp];
  if (corr) out.push(...corr);
  const abbr = abbreviationAliases[cp];
  if (abbr) out.push(...abbr);
  const alt = alternateAliases[cp];
  if (alt) out.push(...alt);
  return out;
}

const ZWJ = 0x200d;

function isHumanFigure(cp: number): boolean {
  // 0x1F466–0x1F9CF covers person emoji; excludes hair components 0x1F9B0–0x1F9B3
  // which are in the range 0x1F9D0+ (emoji with object ZWJ, not people)
  return (cp >= 0x1f466 && cp <= 0x1f9cf) || cp === 0x1f91d;
}

function splitOnZwj(codePoints: number[]): number[][] {
  const result: number[][] = [];
  let current: number[] = [];
  for (const cp of codePoints) {
    if (cp === ZWJ) {
      result.push(current);
      current = [];
    } else current.push(cp);
  }
  result.push(current);
  return result;
}

function detectSkinToneSlots(codePoints: number[], skinToneSupport: boolean): number {
  if (!skinToneSupport) return 0;
  const components = splitOnZwj(codePoints);
  // Two-person direct: exactly 2 components, both human figures
  const twoPersonDirect =
    components.length === 2 &&
    components[0].length > 0 && isHumanFigure(components[0][0]) &&
    components[1].length > 0 && isHumanFigure(components[1][0]);
  // Two-person via joiner: 3 components, outer two are human figures
  // (e.g., 🧑‍🤝‍🧑 = person + handshake + person)
  const twoPersonViaJoiner =
    components.length === 3 &&
    components[0].length > 0 && isHumanFigure(components[0][0]) &&
    components[2].length > 0 && isHumanFigure(components[2][0]);
  if (twoPersonDirect || twoPersonViaJoiner) return 2;
  return 1;
}

const EMOJI_GROUP_TO_CATEGORY: Record<string, string> = {
  'Smileys & Emotion': 'smileys-emotion',
  'People & Body': 'people-body',
  'Animals & Nature': 'animals-nature',
  'Food & Drink': 'food-drink',
  'Travel & Places': 'travel-places',
  Activities: 'activities',
  Objects: 'objects',
  Symbols: 'symbols-emoji',
  Flags: 'flags',
};

function buildEmojiCharacters(): CharacterEntry[] {
  const entries: CharacterEntry[] = [];

  // Build lookup from emoji character → gemoji entry for aliases + tags
  const gemojiByEmoji = new Map<string, { names: string[]; tags: string[] }>();
  for (const g of gemojiData.gemoji) {
    gemojiByEmoji.set(g.emoji, g);
  }

  for (const meta of emojiData) {
    const categoryId = EMOJI_GROUP_TO_CATEGORY[meta.group];
    if (!categoryId) continue;

    const codePoints = meta.cp;
    const firstCp = codePoints[0];
    const char = String.fromCodePoint(...codePoints);

    const gEntry = gemojiByEmoji.get(char);
    const aliases = gEntry ? gEntry.names.map(n => `:${n}:`) : [];
    const tags = gEntry?.tags ?? [];

    // DerivedAge of the (first) code point is the authoritative Unicode version.
    const unicodeVersion = versionForCodePoint(firstCp) ?? meta.emojiVersion;

    entries.push({
      codePoints,
      char,
      hex: `U+${firstCp.toString(16).toUpperCase().padStart(4, '0')}`,
      decimal: firstCp,
      categoryId,
      altCode: null,
      name: meta.name.toUpperCase(),
      aliases,
      tags,
      emoji: {
        group: meta.group,
        subgroup: meta.subgroup,
        emojiVersion: meta.emojiVersion,
        unicodeVersion,
        skinToneSlots: detectSkinToneSlots(codePoints, meta.skinToneSupport),
      },
      unicodeVersion,
    });
  }

  return entries;
}

function makeEntry(codePoint: number, categoryId: string): CharacterEntry {
  return {
    codePoints: [codePoint],
    char: String.fromCodePoint(codePoint),
    hex: `U+${codePoint.toString(16).toUpperCase().padStart(4, '0')}`,
    decimal: codePoint,
    categoryId,
    altCode: unicodeToAlt.get(codePoint) ?? null,
    name: unicodeNames.get(codePoint) ?? draftName(codePoint),
    aliases: getAliases(codePoint),
    tags: [],
    emoji: null,
    unicodeVersion: versionForCodePoint(codePoint),
  };
}

function rangeEntries(start: number, end: number, categoryId: string): CharacterEntry[] {
  const out: CharacterEntry[] = [];
  for (let cp = start; cp <= end; cp++) out.push(makeEntry(cp, categoryId));
  return out;
}

let _cachedData: UnicodeData | null = null;

export function loadUnicodeData(): UnicodeData {
  if (_cachedData) return _cachedData;
  const altCodeEntries: CharacterEntry[] = [];
  for (let altCode = 1; altCode <= 254; altCode++) {
    const cp = altToUnicode.get(altCode);
    if (cp !== undefined) altCodeEntries.push(makeEntry(cp, 'alt-codes'));
  }

  const characters: CharacterEntry[] = [
    ...altCodeEntries,
    ...rangeEntries(0x0021, 0x007e, 'ascii'),
    ...rangeEntries(0x00a0, 0x00ff, 'latin-ext'),
    ...rangeEntries(0x20a0, 0x20cf, 'currency'),
    ...rangeEntries(0x2100, 0x214f, 'letterlike'),
    ...rangeEntries(0x2150, 0x218f, 'number-forms'),
    ...rangeEntries(0x2190, 0x21ff, 'arrows'),
    ...rangeEntries(0x2200, 0x22ff, 'math'),
    ...rangeEntries(0x2300, 0x23ff, 'technical'),
    ...rangeEntries(0x2500, 0x257f, 'box'),
    ...rangeEntries(0x2580, 0x259f, 'blocks'),
    ...rangeEntries(0x25a0, 0x25ff, 'geometric'),
    ...rangeEntries(0x2600, 0x26ff, 'symbols'),
    ...rangeEntries(0x2700, 0x27bf, 'dingbats'),
    ...buildEmojiCharacters(),
  ];

  // Materialize every code point introduced in the latest (draft) version that the
  // curated blocks above don't already cover. Symbols/punctuation join "Misc Symbols";
  // the bulk of new scripts and ideographs (Seal, Jurchen, CJK, …) land in "CJK & Scripts".
  const covered = new Set<number>();
  for (const c of characters) {
    if (c.codePoints.length === 1) covered.add(c.codePoints[0]);
  }
  for (const [start, end, version] of ageRanges) {
    if (version !== LATEST_UNICODE_VERSION) continue;
    for (let cp = start; cp <= end; cp++) {
      if (covered.has(cp)) continue;
      const meta = draftNames[cp.toString(16).toUpperCase()];
      if (!meta) continue; // unnamed (surrogate/noncharacter) — nothing to show
      characters.push(makeEntry(cp, categoryForGeneralCategory(meta[1])));
      covered.add(cp);
    }
  }

  const byCodePoints = new Map<string, CharacterEntry>();
  const byCategory = new Map<string, CharacterEntry[]>();
  const byVersion = new Map<string, CharacterEntry[]>();

  for (const entry of characters) {
    const key = codePointsKey(entry.codePoints);
    if (!byCodePoints.has(key)) byCodePoints.set(key, entry);
    const cat = byCategory.get(entry.categoryId) ?? [];
    cat.push(entry);
    byCategory.set(entry.categoryId, cat);
    if (entry.unicodeVersion) {
      const ver = byVersion.get(entry.unicodeVersion) ?? [];
      ver.push(entry);
      byVersion.set(entry.unicodeVersion, ver);
    }
  }

  const versions = [...byVersion.keys()].sort(compareVersionsDesc);

  _cachedData = { characters, byCodePoints, byCategory, byVersion, versions };
  return _cachedData;
}
