name: Nightly Deployment

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --reporter=verbose
        timeout-minutes: 10

      # We use playwright to generate open graph images
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Setup Git User
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      # Add your deployment steps here
      - name: Deploy to production
        run: |
          npx nx deploy craigory-dev -c $ENV
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          ENV: ${{ github.event.inputs.environment || github.ref_name }}
