name: Nightly Deployment

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
      - preview
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Git User
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      # Add your deployment steps here
      - name: Deploy to production
        run: |
          node ./node_modules/.bin/nx build craigory-dev
          node ./node_modules/.bin/nx deploy craigory-dev -c $ENV
        env:
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          ENV: ${{ github.event.inputs.environment || github.ref_name }}
